# A generic, single database configuration for Alembic.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate new migration files
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# sys.path path, relative to this file.  Defaults to '.'
# This allows Alembic to find our 'app' package
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone =

# limit the conversion of UTC dates to local time
# utc_now = false

# version path separator; as of Alembic 1.0.0, this defaults to os.pathsep.
# version_locations = %(here)s/bar:%(here)s/bat:version_locations

# the database connection URL is loaded dynamically in env.py

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %%(levelname)-5.5s [%%(name)s] %%(message)s
datefmt = %%H:%%M:%%S
